README.md
=> add info about selenium server to docs

lib/http-utils.js
@bootstraponline and I decided to just quickly implement adding user-agent strings to selenium/appium clients for easy identification and bug reporting.
The current format:
`author/libraryName/version`
In the future maybe we can add OperatingSystem as well, but we're going for the MVP right now.
see: https://github.com/appium/ruby_lib/commit/af6d44c6ccd3f32a9553be3c290000421edae92d
=> added user-agent string to requests

lib/commands.js
jsonWire comment has incorrect url scroll command
=> Update jsonWire doc about scroll command

package.json, test/helpers/setup.js
Also update 'request' as it depends on 'node-uuid'
=> Replace deprecated 'node-uuid' with 'uuid'

README.md
Example for how to run WD.js tests on TestingBot
=> Add TestingBot.com example

doc/api.md, doc/jsonwire-full-mapping.md, doc/jsonwire-full.json, lib/commands.js, test/specs/mjson-specs.js
(related to issue: https://github.com/appium/appium/issues/8674)
(@imurchie @jlipps)
=> Added getCurrentPackage method

doc/jsonwire-full.json, doc/release-notes.md, lib/commands.js, package.json
Add methods for the new emulators commands available on appium 1.7.0
=> Add new android emulators commands

lib/webdriver.js
fix(#520)
simply add a check for `jsonData`
=> Check if jsonData exists on error creation for request

doc/api.md, doc/jsonwire-full-mapping.md, doc/jsonwire-full.json, lib/commands.js, test/specs/mjson-specs.js
Adding support for [2 new methods](https://appium.readthedocs.io/en/stable/en/commands/device/clipboard/get-clipboard/) available in **Appium 1.8** server release
@dpgraham @jlipps please review
=> getClipboard / setClipboard methods

doc/api.md, doc/jsonwire-full-mapping.md, doc/jsonwire-full.json, lib/commands.js, test/specs/mjson-specs.js
Implementation for http://appium.io/docs/en/commands/device/keys/is-keyboard-shown/
@jlipps please review
=> isKeyboardShown method

README.md, lib/webdriver.js, test/midway/multi/config-http-specs.js, test/specs/http-specs.js
This fixes linter errors, fixes tests broken by #521, and adds a note about getting chromedriver working.
=> Fix test failures

package.json
Fixes the following:
```
=== npm audit security report ===                        
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ archiver                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ archiver > archiver-utils > lodash                           │ …
```
=> Upgrade archiver and lodash for npm audit security report

doc/api.md, doc/jsonwire-mobile.md, lib/commands.js, lib/element-commands.js, lib/utils.js, test/specs/mjson-specs.js
Functions to search for element with iOS Predicate String.
@dpgraham @jlipps please review
=> find element by ios predicate string

lib/actions.js, lib/commands.js, lib/main.js, test/specs/mjson-actions-specs.js, test/specs/mjson-specs.js
* Here's a code sample: https://github.com/appium/appium/pull/11242
=> Add W3C /actions API to WD

lib/utils.js
Client side code to support the proposal at https://github.com/appium/appium-base-driver/pull/268. (Don't merge until that is merged!)
=> add custom find strategy

lib/actions.js, lib/commands.js, package-lock.json, package.json, test/midway/api-el-suffix-base.js, test/midway/element-specs.js, test/midway/multi/init-specs.js
=> [WIP][#555] Update request dependency

doc/jsonwire-mobile.md, lib/callbacks.js, lib/utils.js, package-lock.json, test/specs/mjson-specs.js
The Espresso Driver has a new selector strategy called `-android datamatcher` (https://github.com/appium/appium/issues/12372)
=> feat: Android Espresso DataMatcher strategy

.gitignore, lib/webdriver.js, package-lock.json
=> Fix hardcoded saucelabs domain

.travis.yml, gulpfile.js
Trying this out to see if PRs from forks can be made to work.
=> build: use built-in sauce connect functionality

lib/commands.js, package.json
Added activateApp command and update version
=> Add Activate App
