lib/commands.js
test/specs/mjson-specs.js

Rather than sending a plain array of actions, send an object with the array as an `actions` property. Without this change touch actions do not work on Sauce Labs.
```js
{
"actions": [
{"action":"press","options":{x: 100, y: 5}},
{"action":"release","options":{}}
]
}
```
rather than
```js
[
{"action":"press","options":{x: 100, y: 5}},
{"action":"release","options":{}}
]
```

Wrap touch action array in object

---

lib/commands.js
test/specs/mjson-specs.js

Appium has added a method to get the time and date off of the device (https://github.com/appium/node-mobile-json-wire-protocol/issues/40). Add the method to access that endpoint.

Add getDeviceTime method

---

lib/webdriver.js

E.g.
```
Driving the web on session: https://saucelabs.com/tests/6767a03ebcc348e386b568ddc56e99b8
```
Handy because you can click while it still runs, and for cross-referencing later (e.g. Travis log->Saucelabs).
Actually I've never used wd with anything other then Saucelabs, hope I got the condition right...

Emit https://saucelabs.com/jobs/SESSIONID link when running on Saucelabs.

---

README.md
examples/async/browserstack.ie.js
examples/async/browserstack.js
examples/promise/browserstack.ie.js
examples/promise/browserstack.js

- Added examples to test on BrowserStack using wd (Async and with Promises).
- Changed README to add example to use constructor `wd.remote` for BrowserStack

Test examples for BrowserStack

---

lib/commands.js

As [documentation](https://github.com/admc/wd/blob/master/doc/api.md), we can use setOrientation with two values `landscape` and `portrait` to rotate on devices.
1. I use two commands below and run pass with Xcode 7 & Appium 1.5.3.
```
.setOrientation('landscape')
.setOrientation('portrait')
```
2. It doesn't work with the Xcode version 8.1 & Appium 1.6.0. It throws errors:
```
Uncaught Error: [setOrientation("landscape")] Error response status: 777
at exports.newError (node_modules/wd/lib/utils.js:139:13)
at node_modules/wd/lib/callbacks.js:33:23
at node_modules/wd/lib/webdriver.js:174:5
at Request._callback (node_modules/wd/lib/http-utils.js:87:7)
at Request.self.callback (node_modules/wd/node_modules/request/request.js:368:22)
at Request.<anonymous> …
```

Fixed issue [setOrientation("landscape")]/ [setOrientation("portrait")] Error response status: 777

---

lib/callbacks.js
lib/commands.js
lib/element-commands.js

I've been seeing a bug where at certain points in my tests, code to
retrieve elements like this:
```
driver.elementsByAccessibilityId("foo bar")
```
would throw an error:
```
[elementsByAccessibilityId("foo bar")] Response value field is not an Array.
```
After looking into the for wd code, I could see this was happening in
`callbacks.js:133`, in code that checked whether the return value was an
array, using `instanceof Array`. When I inspected what this code was
doing at runtime the value really was an array, but `instanceof Array`
was still returning false. Strangely I could reproduce the original
error when I ran my tests via Jest but not when I ran the same code in
the wd repl (where `instanceof Array` would return true at the same place).
It turns out that `instanceof Array` can …

Replaced `<obj> instanceof Array` with `Array.isArray()`

---

lib/tmp.js

```
(node:49216) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
at Object.<anonymous> (/Users/federicozivolo/Progetti/popper-js/node_modules/wd/lib/tmp.js:43:10)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Module.require (module.js:498:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/Users/federicozivolo/Progetti/popper-js/node_modules/wd/lib/commands.js:4:11)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Module.require …
```

Use `tmpdir` to solve Node 7 deprecation

---

package.json

Tests seem to run fine.
Motivation: Get rid of _"wd > archiver > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue"_ warnings.

updated archiver

---

.gitignore
lib/commands.js
lib/utils.js
package.json
scripts/build-browser-scripts.js

Because commands.js was importing scripts using __dirname, this causes problems when you bundle 'wd' into an electron app because the __dirname won't point to the correct directory. Solution is to write an npm script that's fired after install that takes the contents of the browser scripts and then builds them as files that export the Javascript as a string.
(@jlipps Can you have a look at this too)

Build browser scripts after install

---

lib/commands.js
lib/promise-webdriver.js
lib/utils.js

Shouldn't have been removed. It's still being used by setup.js

Add inlineJS back to utils.js

---

lib/webdriver.js

before:
The environment you requested was unavailable.
after(e.g.):
The environment you requested was unavailable.
session not created exception: Chrome version must be >= 59.0.3071.0

Prompt user more info to debug when error comes from init()

---

doc/api.md

Note that I couldn't find any replacements for links starting at `/session/:sessionId/context` and below.
Another thing I thought about is if you should remove the other `.md` files. It's a _huge_ pain to maintain all these links and also most information seems pretty redundant.
Btw, by "broken" I mean they all redirect to https://github.com/seleniumhq/selenium-google-code-issue-archive

links pointing to api docs on code.google.com are "broken"

---

lib/config.js
lib/http-utils.js

This is so that in Appium Desktop when a user creates, we can give them the option to ignore unrecognized certificates.

Add rejectUnauthorized to http config opts

---

lib/callbacks.js
lib/webdriver.js

This adds basic support for the new W3C wire protocol, which fixes Firefox and IE support.
For more details, see https://github.com/SeleniumHQ/selenium/issues/5952#issuecomment-392866840
This PR also includes unrelated test fixes from PR #532
Closes #495

Add basic support for new W3C wire protocol

---

lib/image-element.js

The way the modules are organized, loading `TouchAction` at startup causes it to be in memory before `Element` exists. This means that when you go to use an action you get a TypeError (`TypeError: Right-hand side of 'instanceof' is not callable`) since Element is not a constructor anymore.
See, for instance, the errors in https://api.travis-ci.org/v3/job/395898891/log.txt
Fix by lazily loading the class through a getter.
See also https://github.com/appium/appium/issues/10937

Add getter for TouchAction on ImageElement object

---

lib/commands.js
test/specs/mjson-specs.js

http://appium.io/docs/en/commands/device/keys/press-keycode/
http://appium.io/docs/en/commands/device/keys/long-press-keycode/
`pressKeycode` and `longPressKeycode` should support `flags` to catch up with the latest spec.
We can pass multiple key flags as one number using bit operator, `OR`.
cc @dpgraham @jlipps

add flags for press keycodes

---

lib/webdriver.js

Hello,
I just found a typo in the webdriver.js file which prevent the sessionID to be used and so the remote browser to be managed.
Hope this will help.

Fix a typo on sessionID in webdriver

---

package-lock.json
package.json

Vulnerability details: https://hackerone.com/reports/380873
Lodash changelog: https://github.com/lodash/lodash/wiki/Changelog#v41711

Upgrade lodash to pickup fix for prototype pollution vulnerability

---

README.md
lib/commands.js
package.json
test/midway/wait-for-timeout-specs.js

All tests (`gulp test`) pass for me locally.
At a high level, this seems reasonable, assuming that a timeout error might be caused by the fact that the condition we're checking for has not been met yet. Since we're willing to wait for the condition to become true, we should be willing to retry when a timeout happens.
Concretely, this patch is motivated by the need to stabilize a flaky test in our suite that fails due to a tough bug in ChromeDriver [1, 2, 3]. The failure mode is transient, so retrying fixes the flakiness.
[1] https://bugs.chromium.org/p/chromedriver/issues/detail?id=402
[2] https://bugs.chromium.org/p/chromedriver/issues/detail?id=817
[3]
http://stackoverflow.com/questions/34926866/selenium-chromedriver-timed-out-receiving-message-from-renderer-exception

waitFor considers errors whose message includes "timeout" retriable.

---

gulpfile.js

Fixed 'npm run test' unit tests for Windows platform by modifying gulpfile.js to call **node_modules/mocha/bin/mocha.cmd** on the windows platform.

Fixed 'npm run test' unit tests for Windows platform

---

gulpfile.js

fix: naming of tasks in gulp tasks

---

lib/commands.js
lib/webdriver.js

`/element/active` requires POST method in JsonWireProtocol but W3C WebDriver spec requires GET method.
https://www.w3.org/TR/webdriver/#get-active-element
This patch checks remote WebDriver server speaks JWP or W3C on creating a session and remembers it. Then switch method of `/element/active` looking the flag.

Support W3C get active element command

---

lib/webdriver.js

Currently, the connection is not keep-alive over a test life, during some investigation at Sauce I notice this Appium(webdriver) client is closing TCP connections before any new command.
Here's some Wireshark TCP dump showing it:
👆🏻Before any new command(request) there's a [FIN, ACK]
<hr>
With these changes looking at TCP dumps we can see the socket is kept open, so there's no more resync before new requests 👇🏻

add httpAgent as right now the connection is not kept alive

---

lib/webdriver.js

Having keep-alive sockets causes session close to hang. Until someone makes a general solution to this, I don't think this should be here. Perhaps it could be configurable in `driver.init`?

revert keep-alive until someone figures out how to fix it

---

lib/webdriver.js

Current implementation leads below error when wd tries to connect to https since webdriver always refers http module.
```
[0] TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
[0]     at new ClientRequest (_http_client.js:144:11)
[0]     at Object.request (https.js:309:10)
[0]     at Request.start (/Users/kazu/GitHub/appium-desktop/node_modules/request/request.js:751:32)
[0]     at Request.write (/Users/kazu/GitHub/appium-desktop/node_modules/request/request.js:1497:10)
[0]     at end (/Users/kazu/GitHub/appium-desktop/node_modules/request/request.js:549:18)
[0]     at Immediate._onImmediate (/Users/kazu/GitHub/appium-desktop/node_modules/request/request.js:578:7)
[0]     at processImmediate (internal/timers.js:439:21)
[0] 11:36:14.414 › Killing session …
```

fix: Use https for https
